services:
  dashboard:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /docker/homelabids-masterapi/errorreport:/database:ro
    environment:
      - DB_PATH=/database/errors.db
    restart: unless-stopped
